# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

dragnic_cms:
  resource: "@CmsBundle/Resources/config/routing.yml"
